'use strict';

// ══════════════════════════════════════════════════
// 模型能力注册表 — 每个模型声明自己支持什么
// ══════════════════════════════════════════════════
const MODEL_REGISTRY = {
  // ─── 百炼 Coding Plan 模型 ───
  'qwen3.5-plus': {
    provider: 'bailian',
    label: 'Qwen 3.5 Plus（推荐，支持工具）',
    supportsTools: true,
    supportsStreamOptions: true,
    supportsThinking: true,
    maxTokens: 4096,
  },
  'qwen3-max': {
    provider: 'bailian',
    label: 'Qwen 3 Max（最强推理）',
    supportsTools: true,
    supportsStreamOptions: true,
    supportsThinking: false,
    maxTokens: 4096,
  },
  'qwen3-max-2026-01-23': {
    provider: 'bailian',
    label: 'Qwen 3 Max（最强推理）',
    supportsTools: true,
    supportsStreamOptions: true,
    supportsThinking: false,
    maxTokens: 4096,
  },
  'qwen-plus': {
    provider: 'bailian',
    label: 'Qwen Plus（稳定通用）',
    supportsTools: true,
    supportsStreamOptions: true,
    supportsThinking: false,
    maxTokens: 4096,
  },
  'qwen-max': {
    provider: 'bailian',
    label: 'Qwen Max（最强推理）',
    supportsTools: true,
    supportsStreamOptions: true,
    supportsThinking: false,
    maxTokens: 4096,
  },
  'qwen-turbo': {
    provider: 'bailian',
    label: 'Qwen Turbo（快速便宜）',
    supportsTools: true,
    supportsStreamOptions: true,
    supportsThinking: false,
    maxTokens: 4096,
  },
  'qwen3-coder-next': {
    provider: 'bailian',
    label: 'Qwen 3 Coder Next（代码专用）',
    supportsTools: true,
    supportsStreamOptions: true,
    supportsThinking: false,
    maxTokens: 4096,
  },
  'qwen3-coder-plus': {
    provider: 'bailian',
    label: 'Qwen 3 Coder Plus（代码专用）',
    supportsTools: true,
    supportsStreamOptions: true,
    supportsThinking: false,
    maxTokens: 4096,
  },
  'kimi-k2.6': {
    provider: 'bailian',
    label: 'Kimi K2.6（月之暗面）',
    supportsTools: true,
    supportsStreamOptions: true,
    supportsThinking: false,
    maxTokens: 4096,
  },
  'kimi-k2.5': {
    provider: 'bailian',
    label: 'Kimi K2.5（月之暗面）',
    supportsTools: true,
    supportsStreamOptions: true,
    supportsThinking: false,
    maxTokens: 4096,
  },
  'MiniMax-M2.5': {
    provider: 'bailian',
    label: 'MiniMax M2.5',
    supportsTools: true,
    supportsStreamOptions: true,
    supportsThinking: false,
    maxTokens: 4096,
  },
  // ─── MiniMax 独立模型 ───
  'MiniMax-M2.7': {
    provider: 'minimax',
    label: 'MiniMax M2.7（最新，自我迭代）',
    supportsTools: true,
    supportsStreamOptions: true,
    supportsThinking: true,
    thinkingFormat: 'think_tags',
    maxTokens: 8192,
  },
  'MiniMax-M2.7-highspeed': {
    provider: 'minimax',
    label: 'MiniMax M2.7 极速版（100tps）',
    supportsTools: true,
    supportsStreamOptions: true,
    supportsThinking: true,
    thinkingFormat: 'think_tags',
    maxTokens: 8192,
  },
  'MiniMax-M2.5-standalone': {
    provider: 'minimax',
    label: 'MiniMax M2.5（顶尖性能）',
    supportsTools: true,
    supportsStreamOptions: true,
    supportsThinking: true,
    thinkingFormat: 'think_tags',
    maxTokens: 8192,
  },
  'MiniMax-M2.5-highspeed': {
    provider: 'minimax',
    label: 'MiniMax M2.5 极速版（100tps）',
    supportsTools: true,
    supportsStreamOptions: true,
    supportsThinking: true,
    thinkingFormat: 'think_tags',
    maxTokens: 8192,
  },
  'MiniMax-M2.1': {
    provider: 'minimax',
    label: 'MiniMax M2.1（多语言编程）',
    supportsTools: true,
    supportsStreamOptions: true,
    supportsThinking: true,
    thinkingFormat: 'think_tags',
    maxTokens: 4096,
  },
  'MiniMax-M2.1-highspeed': {
    provider: 'minimax',
    label: 'MiniMax M2.1 极速版（100tps）',
    supportsTools: true,
    supportsStreamOptions: true,
    supportsThinking: true,
    thinkingFormat: 'think_tags',
    maxTokens: 4096,
  },
  'MiniMax-M2': {
    provider: 'minimax',
    label: 'MiniMax M2（高效编码）',
    supportsTools: true,
    supportsStreamOptions: true,
    supportsThinking: true,
    thinkingFormat: 'think_tags',
    maxTokens: 4096,
  },
  'glm-5': {
    provider: 'bailian',
    label: 'GLM 5（智谱）',
    supportsTools: true,
    supportsStreamOptions: true,
    supportsThinking: false,
    maxTokens: 4096,
  },
  'glm-4.7': {
    provider: 'bailian',
    label: 'GLM 4.7（智谱）',
    supportsTools: true,
    supportsStreamOptions: true,
    supportsThinking: false,
    maxTokens: 4096,
  },
  'deepseek-v3': {
    provider: 'bailian',
    label: 'DeepSeek V3（百炼版，不支持工具）',
    supportsTools: false,       // ← 关键！
    supportsStreamOptions: true,
    supportsThinking: false,
    maxTokens: 4096,
  },
  'deepseek-r1': {
    provider: 'bailian',
    label: 'DeepSeek R1（百炼版，深度推理）',
    supportsTools: false,       // ← 关键！
    supportsStreamOptions: true,
    supportsThinking: true,
    maxTokens: 4096,
  },
  // ─── DeepSeek 官方 API ───
  'deepseek-v4-flash': {
    provider: 'deepseek',
    label: 'DeepSeek V4 Flash（通用，推荐）',
    supportsTools: true,
    supportsStreamOptions: false,  // DeepSeek 官方不支持
    supportsThinking: false,
    // DeepSeek max_tokens 包含思考(COT)部分，思考与正文共享同一预算（官方上限64K/默认32K）。
    // 8192 太小：该模型即使 supportsThinking:false 仍会内部烧思考token(无法关闭)，
    // 烧掉一半预算后剩余不足以写完较长工具调用参数(如 canvas SVG)，导致输出被截断、
    // 工具调用JSON不完整而静默失败。16000 留出充足余量，仍远低于官方上限。
    maxTokens: 16000,
  },
  'deepseek-v4-pro': {
    provider: 'deepseek',
    label: 'DeepSeek V4 Pro（深度推理）',
    supportsTools: false,
    supportsStreamOptions: false,
    supportsThinking: true,
    // 深度推理模型思考更重，同样按"思考+正文共享预算"原则给更大余量。
    maxTokens: 24000,
  },
  'deepseek-chat': {
    provider: 'deepseek',
    label: 'DeepSeek Chat（旧版，2026/07/24 弃用）',
    supportsTools: true,
    supportsStreamOptions: false,
    supportsThinking: false,
    maxTokens: 4096,
  },
  'deepseek-reasoner': {
    provider: 'deepseek',
    label: 'DeepSeek Reasoner（旧版，2026/07/24 弃用）',
    supportsTools: false,
    supportsStreamOptions: false,
    supportsThinking: true,
    maxTokens: 4096,
  },
  // ─── Google Gemini（OpenAI 兼容端点 generativelanguage…/v1beta/openai）───
  'gemini-3.5-flash': {
    provider: 'google',
    label: 'Gemini 3.5 Flash',
    supportsTools: true,
    supportsStreamOptions: false,
    supportsThinking: true,
    maxTokens: 65535,
  },
  'gemini-3.1-pro-preview': {
    provider: 'google',
    label: 'Gemini 3.1 Pro Preview',
    supportsTools: true,
    supportsStreamOptions: false,
    supportsThinking: true,
    maxTokens: 65536,
  },
  'gemini-3.1-pro-preview-customtools': {
    provider: 'google',
    label: 'Gemini 3.1 Pro Preview Custom Tools',
    supportsTools: true,
    supportsStreamOptions: false,
    supportsThinking: true,
    maxTokens: 65536,
  },
  'gemini-3-flash-preview': {
    provider: 'google',
    label: 'Gemini 3 Flash Preview',
    supportsTools: true,
    supportsStreamOptions: false,
    supportsThinking: true,
    maxTokens: 65536,
  },
  'gemini-3.1-flash-lite': {
    provider: 'google',
    label: 'Gemini 3.1 Flash-Lite',
    supportsTools: true,
    supportsStreamOptions: false,
    supportsThinking: true,
    maxTokens: 65535,
  },
  'gemini-3.1-flash-lite-preview': {
    provider: 'google',
    label: 'Gemini 3.1 Flash-Lite Preview',
    supportsTools: true,
    supportsStreamOptions: false,
    supportsThinking: true,
    maxTokens: 65535,
  },
  'gemini-2.5-pro': {
    provider: 'google',
    label: 'Gemini 2.5 Pro',
    supportsTools: true,
    supportsStreamOptions: false,
    supportsThinking: true,
    maxTokens: 8192,
  },
  'gemini-2.5-flash': {
    provider: 'google',
    label: 'Gemini 2.5 Flash',
    supportsTools: true,
    supportsStreamOptions: false,
    supportsThinking: true,
    maxTokens: 8192,
  },
  'gemini-2.5-flash-lite': {
    provider: 'google',
    label: 'Gemini 2.5 Flash-Lite',
    supportsTools: true,
    supportsStreamOptions: false,
    supportsThinking: true,
    maxTokens: 8192,
  },
  'gemini-2.0-flash': {
    provider: 'google',
    label: 'Gemini 2.0 Flash',
    supportsTools: false,
    supportsStreamOptions: false,
    supportsThinking: false,
    maxTokens: 8192,
  },
  'gemini-2.0-flash-lite': {
    provider: 'google',
    label: 'Gemini 2.0 Flash-Lite',
    supportsTools: false,
    supportsStreamOptions: false,
    supportsThinking: false,
    maxTokens: 8192,
  },
  'gemini-1.5-flash': {
    provider: 'google',
    label: 'Gemini 1.5 Flash',
    supportsTools: false,
    supportsStreamOptions: false,
    supportsThinking: false,
    maxTokens: 8192,
  },
  'gemini-1.5-flash-8b': {
    provider: 'google',
    label: 'Gemini 1.5 Flash-8B',
    supportsTools: false,
    supportsStreamOptions: false,
    supportsThinking: false,
    maxTokens: 8192,
  },
  'gemini-1.5-pro': {
    provider: 'google',
    label: 'Gemini 1.5 Pro',
    supportsTools: false,
    supportsStreamOptions: false,
    supportsThinking: false,
    maxTokens: 8192,
  },
};

module.exports = { MODEL_REGISTRY };
