import type { Artifact } from '../types/artifact';

export const MOCK_ARTIFACTS: Artifact[] = [
  {
    id: 'art-team-template-v1',
    projectId: 'proj-changye-weiming',
    type: 'team_template',
    scope: 'project',
    scopeId: 'proj-changye-weiming',
    version: 1,
    content: null,
    contentPreview:
      '模板：多人演播有声小说。默认链路：项目摄入 -> 作品分析 -> 场景拆分 -> 文本改编 -> 角色音标注 -> 演播设计 -> 质检审核 -> 打包交付。',
    status: 'approved',
    isFrozen: true,
    createdAt: '2026-04-25T09:00:00Z',
  },
  {
    id: 'art-project-context-v1',
    projectId: 'proj-changye-weiming',
    type: 'project_context',
    scope: 'project',
    scopeId: 'proj-changye-weiming',
    version: 1,
    content: null,
    contentPreview:
      '{ "genre": "悬疑刑侦", "source": "小说", "adaptationBoundary": "只改表达，不改事实", "currentMode": "单章试跑", "humanCheckpoints": ["角色音回绑", "质检打回"] }',
    status: 'approved',
    isFrozen: true,
    createdAt: '2026-04-25T09:00:04Z',
  },
  {
    id: 'art-chapters-idx-v1',
    projectId: 'proj-changye-weiming',
    type: 'chapter_index',
    scope: 'project',
    scopeId: 'proj-changye-weiming',
    version: 1,
    content: null,
    contentPreview:
      '[\n  { "idx": 1, "title": "樟木箱", "time": "2015年3月", "chars": 3240 },\n  { "idx": 2, "title": "夜", "time": "2015年3月", "chars": 2890 },\n  { "idx": 3, "title": "滋啦", "time": "1986年3月", "chars": 3105 }\n]',
    status: 'approved',
    isFrozen: true,
    createdAt: '2026-04-24T08:30:04Z',
  },
  {
    id: 'art-plot-lock-ch1-v1',
    projectId: 'proj-changye-weiming',
    type: 'plot_lock',
    scope: 'chapter',
    scopeId: 'ch-01',
    version: 1,
    content: null,
    contentPreview:
      '第1章锁定信息：周佳宁回旧屋；周婉云交代收拾阁楼；周佳宁发现樟木箱、笔记本、对讲机和手铐；不得提前解释对讲机异常。',
    status: 'approved',
    isFrozen: true,
    createdAt: '2026-04-25T09:01:30Z',
  },
  {
    id: 'art-char-profile-v1',
    projectId: 'proj-changye-weiming',
    type: 'character_profile',
    scope: 'project',
    scopeId: 'proj-changye-weiming',
    version: 1,
    content: null,
    contentPreview:
      '[\n  { "id": "zhou_jianing", "name": "周佳宁", "role": "2015线主角", "voice_style": "克制、理性、偏冷静" },\n  { "id": "zhou_wanyun", "name": "周婉云", "role": "母亲", "voice_style": "疲惫、回避、压抑" },\n  { "id": "zhou_zhenshan", "name": "周振山", "role": "1986线关键人物", "voice_style": "基层刑警、硬朗克制" }\n]',
    status: 'approved',
    isFrozen: true,
    createdAt: '2026-04-24T08:32:10Z',
  },
  {
    id: 'art-artifact-tracker-v1',
    projectId: 'proj-changye-weiming',
    type: 'artifact_tracker',
    scope: 'project',
    scopeId: 'proj-changye-weiming',
    version: 1,
    content: null,
    contentPreview:
      '[\n  { "id": "camphor_trunk", "name": "樟木箱", "significance": "开启主线，连接双时空" },\n  { "id": "walkie_talkie", "name": "对讲机", "significance": "跨时空通话载体，暂不解释机制" },\n  { "id": "notebooks", "name": "笔记本", "significance": "案件与欠字线索载体" }\n]',
    status: 'approved',
    isFrozen: true,
    createdAt: '2026-04-24T08:32:15Z',
  },
  {
    id: 'art-style-profile-v1',
    projectId: 'proj-changye-weiming',
    type: 'style_profile',
    scope: 'project',
    scopeId: 'proj-changye-weiming',
    version: 1,
    content: null,
    contentPreview:
      '{ "tone": "冷峻、克制、物件特写密集", "narrative_pov": "第三人称有限视角", "signature": ["气味与触感描写", "旧物承载悬念"] }',
    status: 'approved',
    isFrozen: true,
    createdAt: '2026-04-24T08:32:20Z',
  },
  {
    id: 'art-scene-breakdown-ch1-v1',
    projectId: 'proj-changye-weiming',
    type: 'scene_breakdown',
    scope: 'chapter',
    scopeId: 'ch-01',
    version: 1,
    content: null,
    contentPreview:
      '[\n  { "scene_id": "ch01-sc01", "summary": "周佳宁和周婉云进入旧屋，交代收拾阁楼" },\n  { "scene_id": "ch01-sc02", "summary": "周佳宁上阁楼，发现樟木箱" },\n  { "scene_id": "ch01-sc03", "summary": "箱内出现笔记本、对讲机和手铐" }\n]',
    status: 'approved',
    isFrozen: true,
    createdAt: '2026-04-25T09:03:00Z',
  },
  {
    id: 'art-adapted-script-ch1-sc1-v1',
    projectId: 'proj-changye-weiming',
    type: 'adapted_script',
    scope: 'scene',
    scopeId: 'ch01-sc01',
    version: 1,
    content: null,
    contentPreview:
      '【旁白】三月的风，从楼道的窗户缝里灌进来，带着一股铁锈味，还有灰尘味。\n\n【周婉云】东西都搬得差不多了。就剩阁楼上那些旧东西，你自己上去收拾一下。\n\n【周佳宁】嗯。',
    status: 'reviewing',
    isFrozen: false,
    createdAt: '2026-04-25T09:12:00Z',
  },
  {
    id: 'art-voice-registry-ch1-v1',
    projectId: 'proj-changye-weiming',
    type: 'voice_registry',
    scope: 'chapter',
    scopeId: 'ch-01',
    version: 1,
    content: null,
    contentPreview:
      '[\n  { "voice_tag": "周佳宁", "category": "明确角色对白", "status": "已确认", "cast": "主役，不建议兼配" },\n  { "voice_tag": "周婉云", "category": "明确角色对白", "status": "已确认", "cast": "协役，可人工确认兼配" },\n  { "voice_tag": "未定记录者A", "category": "未定来源角色音", "status": "独立占位，可回绑", "delivery": "OS候选" }\n]',
    status: 'reviewing',
    isFrozen: false,
    createdAt: '2026-04-25T09:14:50Z',
  },
  {
    id: 'art-performance-design-ch1-v1',
    projectId: 'proj-changye-weiming',
    type: 'performance_design',
    scope: 'chapter',
    scopeId: 'ch-01',
    version: 0,
    content: null,
    contentPreview:
      '待生成：将基于改编稿和角色音表补充 BGM、SFX、CV 情绪、气息、动作感与声场设计。',
    status: 'draft',
    isFrozen: false,
    createdAt: '2026-04-25T09:15:00Z',
  },
];
