import type { Artifact } from '../types/artifact';

export const MOCK_ARTIFACTS: Artifact[] = [
  {
    id: 'art-team-template-v1',
    projectId: 'proj-changye-weiming',
    type: 'team_template',
    scope: 'project',
    scopeId: 'proj-changye-weiming',
    version: 1,
    content: null,
    contentPreview:
      '多人演播有声小说模板\n\n制作链路：项目摄入 -> 作品分析 -> 场景拆分 -> 文本改编 -> 角色音标注 -> 演播设计 -> 质检审核 -> 打包交付。\n\n当前目标：先跑通第1章样章，确认文本、角色音、演播标注和质检报告的交付形态。',
    status: 'approved',
    isFrozen: true,
    createdAt: '2026-04-25T09:00:00Z',
  },
  {
    id: 'art-project-context-v1',
    projectId: 'proj-changye-weiming',
    type: 'project_context',
    scope: 'project',
    scopeId: 'proj-changye-weiming',
    version: 1,
    content: null,
    contentPreview:
      '项目上下文\n\n题材：悬疑刑侦\n原文类型：小说\n当前模式：单章试跑\n改编边界：只改表达，不改事实；只提升听感、演播连贯性和制作可读性。\n\n需要人工确认：角色音回绑、质检打回、正式导出。',
    status: 'approved',
    isFrozen: true,
    createdAt: '2026-04-25T09:00:04Z',
  },
  {
    id: 'art-chapters-idx-v1',
    projectId: 'proj-changye-weiming',
    type: 'chapter_index',
    scope: 'project',
    scopeId: 'proj-changye-weiming',
    version: 1,
    content: null,
    contentPreview:
      '章节索引\n\n第1章 樟木箱：2015年3月，临水市，约3240字\n第2章 夜：2015年3月，临水市，约2890字\n第3章 滋啦：1986年3月，临水市，约3105字\n\n当前试跑章节：第1章 樟木箱',
    status: 'approved',
    isFrozen: true,
    createdAt: '2026-04-24T08:30:04Z',
  },
  {
    id: 'art-plot-lock-ch1-v1',
    projectId: 'proj-changye-weiming',
    type: 'plot_lock',
    scope: 'chapter',
    scopeId: 'ch-01',
    version: 1,
    content: null,
    contentPreview:
      '第1章锁定信息：周佳宁回旧屋；周婉云交代收拾阁楼；周佳宁发现樟木箱、笔记本、对讲机和手铐；不得提前解释对讲机异常。',
    status: 'approved',
    isFrozen: true,
    createdAt: '2026-04-25T09:01:30Z',
  },
  {
    id: 'art-char-profile-v1',
    projectId: 'proj-changye-weiming',
    type: 'character_profile',
    scope: 'project',
    scopeId: 'proj-changye-weiming',
    version: 1,
    content: null,
    contentPreview:
      '人物档案摘要\n\n周佳宁：2015线主角。声线建议偏冷静、克制、理性，情绪不外放。\n周婉云：母亲角色。声线建议疲惫、回避、压抑，语气不要刻薄。\n周振山：1986线关键人物。声线建议基层刑警质感，硬朗但克制。',
    status: 'approved',
    isFrozen: true,
    createdAt: '2026-04-24T08:32:10Z',
  },
  {
    id: 'art-artifact-tracker-v1',
    projectId: 'proj-changye-weiming',
    type: 'artifact_tracker',
    scope: 'project',
    scopeId: 'proj-changye-weiming',
    version: 1,
    content: null,
    contentPreview:
      '物件追踪摘要\n\n樟木箱：开启主线，连接旧屋、周振山笔记和双时空线索。\n对讲机：跨时空通话载体，当前阶段只呈现异常，不解释机制。\n笔记本：案件、年份和“欠”字线索载体，需保持悬疑信息顺序。',
    status: 'approved',
    isFrozen: true,
    createdAt: '2026-04-24T08:32:15Z',
  },
  {
    id: 'art-style-profile-v1',
    projectId: 'proj-changye-weiming',
    type: 'style_profile',
    scope: 'project',
    scopeId: 'proj-changye-weiming',
    version: 1,
    content: null,
    contentPreview:
      '风格画像\n\n整体基调：冷峻、克制、旧物压迫感强。\n叙事视角：第三人称有限视角，贴近周佳宁感知。\n风格重点：气味、触感、声音细节要保留；旧物承担悬念，不要提前解释。',
    status: 'approved',
    isFrozen: true,
    createdAt: '2026-04-24T08:32:20Z',
  },
  {
    id: 'art-scene-breakdown-ch1-v1',
    projectId: 'proj-changye-weiming',
    type: 'scene_breakdown',
    scope: 'chapter',
    scopeId: 'ch-01',
    version: 1,
    content: null,
    contentPreview:
      '第1章场景拆分\n\n场景 1：周佳宁和周婉云进入旧屋，周婉云交代她上阁楼收拾旧物。\n场景 2：周佳宁穿过客厅到阳台，踩着旧木梯进入阁楼。\n场景 3：周佳宁发现樟木箱，箱内出现笔记本、对讲机和手铐。\n\n制作提示：本章前半段以旧屋空间、气味和物件悬疑为主，不提前解释对讲机。',
    status: 'approved',
    isFrozen: true,
    createdAt: '2026-04-25T09:03:00Z',
  },
  {
    id: 'art-adapted-script-ch1-sc1-v1',
    projectId: 'proj-changye-weiming',
    type: 'adapted_script',
    scope: 'scene',
    scopeId: 'ch01-sc01',
    version: 1,
    content: null,
    contentPreview:
      '【旁白】三月的风，从楼道的窗户缝里灌进来，带着一股铁锈味，还有灰尘味。\n\n【周婉云】东西都搬得差不多了。就剩阁楼上那些旧东西，你自己上去收拾一下。\n\n【周佳宁】嗯。',
    status: 'reviewing',
    isFrozen: false,
    createdAt: '2026-04-25T09:12:00Z',
  },
  {
    id: 'art-voice-registry-ch1-v1',
    projectId: 'proj-changye-weiming',
    type: 'voice_registry',
    scope: 'chapter',
    scopeId: 'ch-01',
    version: 1,
    content: null,
    contentPreview:
      '角色音表\n\n周佳宁：明确角色对白，主役，不建议兼配。\n周婉云：明确角色对白，协役，可由统筹确认是否兼配。\n未定记录者A：未定来源角色音，独立占位，可后续回绑；建议标为 OS 候选，不直接归旁白。\n\n待人工确认：未定记录者A 是否需要提前独立锁 CV。',
    status: 'reviewing',
    isFrozen: false,
    createdAt: '2026-04-25T09:14:50Z',
  },
  {
    id: 'art-performance-design-ch1-v1',
    projectId: 'proj-changye-weiming',
    type: 'performance_design',
    scope: 'chapter',
    scopeId: 'ch-01',
    version: 0,
    content: null,
    contentPreview:
      '待生成：将基于改编稿和角色音表补充 BGM、SFX、CV 情绪、气息、动作感与声场设计。',
    status: 'draft',
    isFrozen: false,
    createdAt: '2026-04-25T09:15:00Z',
  },
];
