import type { Stage } from '../types/stage';

export const MOCK_STAGES: Stage[] = [
  {
    idx: 0,
    id: 'stage-ingestion',
    name: '摄入与切分',
    description: '从原稿中识别章节边界，建立章节索引与时空标签',
    agentRef: 'ingest.chapter_splitter@1.0',
    status: 'done',
    tokensUsed: 0,
    runtimeSeconds: 4,
    artifactCount: 1,
    startedAt: '2026-04-24T08:30:00Z',
    finishedAt: '2026-04-24T08:30:04Z',
  },
  {
    idx: 1,
    id: 'stage-global-analysis',
    name: '全局分析',
    description: '基于全文采样建立作品级知识档案。4 个分析 Agent 并行执行',
    agentRef: 'analyzer.* (4 个并行)',
    status: 'done',
    tokensUsed: 41200,
    runtimeSeconds: 138,
    artifactCount: 4,
    startedAt: '2026-04-24T08:30:04Z',
    finishedAt: '2026-04-24T08:32:22Z',
  },
  {
    idx: 2,
    id: 'stage-chapter-analysis',
    name: '章节分析',
    description: '按章节切分场景、标注对白与旁白、识别情绪曲线',
    agentRef: 'analyzer.scene_splitter@1.0',
    status: 'done',
    tokensUsed: 68400,
    runtimeSeconds: 302,
    artifactCount: 28,
    startedAt: '2026-04-24T08:32:22Z',
    finishedAt: '2026-04-24T08:37:24Z',
  },
  {
    idx: 3,
    id: 'stage-distillation',
    name: '提炼与重组',
    description: '识别可删减的细节，保留伏笔，给出演播时长估算',
    agentRef: 'distiller.content_filter@1.0',
    status: 'done',
    tokensUsed: 29300,
    runtimeSeconds: 104,
    artifactCount: 28,
    startedAt: '2026-04-24T08:37:24Z',
    finishedAt: '2026-04-24T08:39:08Z',
  },
  {
    idx: 4,
    id: 'stage-rewriting',
    name: '剧本化重写',
    description: '按场景单位将原文改写为有声书演播台本',
    agentRef: 'rewriter.audiobook@1.0',
    status: 'running',
    tokensUsed: 184000,
    runtimeSeconds: 522,
    artifactCount: 12,
    startedAt: '2026-04-24T08:39:08Z',
  },
  {
    idx: 5,
    id: 'stage-consistency',
    name: '一致性审核',
    description: '人物称谓、物件描述、时空逻辑、风格匹配度的自动审核',
    agentRef: 'reviewer.consistency@1.0',
    status: 'pending',
    tokensUsed: 0,
    runtimeSeconds: 0,
    artifactCount: 0,
  },
  {
    idx: 6,
    id: 'stage-human-review',
    name: '人工审校',
    description: '人工逐场景审校，可打回任一前置阶段',
    agentRef: '人工 · Zilong',
    status: 'review',
    tokensUsed: 0,
    runtimeSeconds: 0,
    artifactCount: 3,
  },
  {
    idx: 7,
    id: 'stage-packaging',
    name: '打包交付',
    description: '导出标准格式剧本、生成录制任务包、版本封版归档',
    agentRef: 'packager.audiobook@1.0',
    status: 'pending',
    tokensUsed: 0,
    runtimeSeconds: 0,
    artifactCount: 0,
  },
];
