import type { Stage } from '../types/stage';

export const MOCK_STAGES: Stage[] = [
  {
    idx: 0,
    id: 'stage-ingestion',
    name: '项目摄入',
    description: '导入原文，识别章节边界，建立章节索引和项目上下文。',
    agentRef: 'ingest.chapter_splitter@1.0',
    status: 'done',
    inputArtifactTypes: [],
    outputArtifactTypes: ['chapter_index', 'project_context'],
    tokensUsed: 0,
    runtimeSeconds: 4,
    artifactCount: 2,
    startedAt: '2026-04-24T08:30:00Z',
    finishedAt: '2026-04-24T08:30:04Z',
  },
  {
    idx: 1,
    id: 'stage-analysis',
    name: '作品分析',
    description: '建立剧情锁定表、角色档案、物件追踪、时间线和风格画像。',
    agentRef: 'analyzer.project_pack@1.0',
    status: 'done',
    inputArtifactTypes: ['chapter_index', 'project_context'],
    outputArtifactTypes: ['plot_lock', 'character_profile', 'artifact_tracker', 'timeline', 'style_profile'],
    tokensUsed: 41200,
    runtimeSeconds: 138,
    artifactCount: 5,
    startedAt: '2026-04-24T08:30:04Z',
    finishedAt: '2026-04-24T08:32:22Z',
  },
  {
    idx: 2,
    id: 'stage-scene-map',
    name: '场景拆分',
    description: '按章节拆出可制作场景，标注旁白、对白、时空和情绪曲线。',
    agentRef: 'analyzer.scene_splitter@1.0',
    status: 'done',
    inputArtifactTypes: ['chapter_index', 'plot_lock'],
    outputArtifactTypes: ['scene_breakdown'],
    tokensUsed: 68400,
    runtimeSeconds: 302,
    artifactCount: 28,
    startedAt: '2026-04-24T08:32:22Z',
    finishedAt: '2026-04-24T08:37:24Z',
  },
  {
    idx: 3,
    id: 'stage-text-adaptation',
    name: '文本改编',
    description: '按规则把原文改写为更适合多人演播的口语化台本。',
    agentRef: 'adapter.audiobook_text_rewriter@1.0',
    status: 'running',
    inputArtifactTypes: ['scene_breakdown', 'plot_lock', 'style_profile'],
    outputArtifactTypes: ['adapted_script'],
    ruleDocPath: 'docs/03_specs/内容创作工作台/多人演播有声小说改编规则.md',
    tokensUsed: 84200,
    runtimeSeconds: 241,
    artifactCount: 1,
    startedAt: '2026-04-25T09:10:00Z',
  },
  {
    idx: 4,
    id: 'stage-voice-classification',
    name: '角色音标注',
    description: '识别明确角色音、未定来源角色音、功能性声音和可回绑占位。',
    agentRef: 'classifier.voice_role_marker@1.0',
    status: 'review',
    inputArtifactTypes: ['adapted_script', 'character_profile'],
    outputArtifactTypes: ['voice_registry'],
    ruleDocPath: 'docs/03_specs/内容创作工作台/多人演播角色音分类标注规则.md',
    requiresHumanReview: true,
    tokensUsed: 12600,
    runtimeSeconds: 56,
    artifactCount: 1,
    startedAt: '2026-04-25T09:14:01Z',
  },
  {
    idx: 5,
    id: 'stage-performance-design',
    name: '演播设计',
    description: '为台本补充音效、BGM、CV 情绪、气息、动作感和声场标注。',
    agentRef: 'designer.performance_audio@1.0',
    status: 'pending',
    inputArtifactTypes: ['adapted_script', 'voice_registry'],
    outputArtifactTypes: ['performance_design'],
    ruleDocPath: 'docs/03_specs/内容创作工作台/多人演播演播设计规则.md',
    tokensUsed: 0,
    runtimeSeconds: 0,
    artifactCount: 0,
  },
  {
    idx: 6,
    id: 'stage-quality-review',
    name: '质检审核',
    description: '检查忠实度、可听度、角色音归类、演播设计和返工风险。',
    agentRef: 'reviewer.production_quality@1.0',
    status: 'pending',
    inputArtifactTypes: ['adapted_script', 'voice_registry', 'performance_design'],
    outputArtifactTypes: ['review_report'],
    ruleDocPath: 'docs/03_specs/内容创作工作台/多人演播质检规则.md',
    requiresHumanReview: true,
    tokensUsed: 0,
    runtimeSeconds: 0,
    artifactCount: 0,
  },
  {
    idx: 7,
    id: 'stage-export',
    name: '打包交付',
    description: '导出剧组统筹表、演播台本、角色音表、演播标注和质检报告。',
    agentRef: 'packager.content_delivery@1.0',
    status: 'pending',
    inputArtifactTypes: ['adapted_script', 'voice_registry', 'performance_design', 'review_report'],
    outputArtifactTypes: ['final_package'],
    tokensUsed: 0,
    runtimeSeconds: 0,
    artifactCount: 0,
  },
];
