import type { AgentDef } from '../types/agent';

export const MOCK_AGENTS: AgentDef[] = [
  {
    id: 'ingest.chapter_splitter',
    version: '1.0',
    role: '项目摄入与章节切分',
    stageIdx: 0,
    preferredModel: '规则驱动 + 小模型',
    inputArtifactTypes: [],
    outputArtifactTypes: ['chapter_index', 'project_context'],
    canModifySource: false,
    requiresHumanReview: false,
    description: '从原文中识别章节、标题、时空标签和基础字数信息。',
  },
  {
    id: 'analyzer.project_pack',
    version: '1.0',
    role: '作品级分析包',
    stageIdx: 1,
    preferredModel: 'DeepSeek R1',
    inputArtifactTypes: ['chapter_index', 'project_context'],
    outputArtifactTypes: ['plot_lock', 'character_profile', 'artifact_tracker', 'timeline', 'style_profile'],
    canModifySource: false,
    requiresHumanReview: false,
    description: '建立剧情锁定、人物、物件、时间线和风格基线。',
  },
  {
    id: 'analyzer.scene_splitter',
    version: '1.0',
    role: '章节场景拆分',
    stageIdx: 2,
    preferredModel: 'Qwen Max',
    inputArtifactTypes: ['chapter_index', 'plot_lock'],
    outputArtifactTypes: ['scene_breakdown'],
    canModifySource: false,
    requiresHumanReview: false,
    description: '把章节拆成可制作场景，为后续改编和演播设计提供结构。',
  },
  {
    id: 'adapter.audiobook_text_rewriter',
    version: '1.0',
    role: '多人演播文本改编',
    stageIdx: 3,
    preferredModel: 'Claude Sonnet',
    inputArtifactTypes: ['scene_breakdown', 'plot_lock', 'style_profile'],
    outputArtifactTypes: ['adapted_script'],
    ruleDocPath: 'docs/03_specs/多人演播有声小说改编规则.md',
    canModifySource: true,
    requiresHumanReview: true,
    description: '只改表达和听感，不改事实、线索、人物关系和悬念顺序。',
  },
  {
    id: 'classifier.voice_role_marker',
    version: '1.0',
    role: '角色音分类标注',
    stageIdx: 4,
    preferredModel: 'Claude Sonnet',
    inputArtifactTypes: ['adapted_script', 'character_profile'],
    outputArtifactTypes: ['voice_registry'],
    ruleDocPath: 'docs/03_specs/多人演播角色音分类标注规则.md',
    canModifySource: false,
    requiresHumanReview: true,
    description: '识别明确角色音、未定来源角色音、功能性声音和可回绑占位。',
  },
  {
    id: 'designer.performance_audio',
    version: '1.0',
    role: '演播设计',
    stageIdx: 5,
    preferredModel: 'Claude Sonnet',
    inputArtifactTypes: ['adapted_script', 'voice_registry'],
    outputArtifactTypes: ['performance_design'],
    ruleDocPath: 'docs/03_specs/多人演播演播设计规则.md',
    canModifySource: false,
    requiresHumanReview: true,
    description: '补充音效、BGM、CV 情绪、气息、动作感和声场设计。',
  },
  {
    id: 'reviewer.production_quality',
    version: '1.0',
    role: '制作质检',
    stageIdx: 6,
    preferredModel: 'DeepSeek R1',
    inputArtifactTypes: ['adapted_script', 'voice_registry', 'performance_design'],
    outputArtifactTypes: ['review_report'],
    ruleDocPath: 'docs/03_specs/多人演播质检规则.md',
    canModifySource: false,
    requiresHumanReview: true,
    description: '检查忠实度、可听度、角色音归类、演播设计和返工风险。',
  },
  {
    id: 'packager.content_delivery',
    version: '1.0',
    role: '制作包导出',
    stageIdx: 7,
    preferredModel: '规则驱动',
    inputArtifactTypes: ['adapted_script', 'voice_registry', 'performance_design', 'review_report'],
    outputArtifactTypes: ['final_package'],
    canModifySource: false,
    requiresHumanReview: false,
    description: '导出剧组统筹表、演播台本、角色音表和质检报告。',
  },
];
