/** Conversation turn lifecycle — single source of truth for Phase 2 FSM. */

export enum TurnPhase {
  IDLE = 'IDLE',
  USER_TYPING = 'USER_TYPING',
  USER_SUBMIT = 'USER_SUBMIT',
  USER_COMMITTED = 'USER_COMMITTED',

  REQUEST_DISPATCHED = 'REQUEST_DISPATCHED',
  MODEL_THINKING = 'MODEL_THINKING',
  STREAM_OPEN = 'STREAM_OPEN',

  STREAMING = 'STREAMING',
  STREAM_PAUSED = 'STREAM_PAUSED',
  STREAM_COMPLETE = 'STREAM_COMPLETE',

  RENDER_COMPLETE = 'RENDER_COMPLETE',
  TURN_FINISHED = 'TURN_FINISHED',
}
